# Generated by Django 5.0.6 on 2024-05-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
