# Generated by Django 5.0.6 on 2024-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_air'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='category',
        ),
    ]
