# Generated by Django 5.0.6 on 2024-05-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_air_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='product',
        ),
    ]
