# Generated by Django 5.0.6 on 2024-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_air_image_yol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='about',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='yol',
            name='about',
            field=models.CharField(max_length=1500),
        ),
    ]
